Api issue with latest version of librosa
Not sure if my local setup is to blame for this but I needed to downgrade librosa to use a pre 0.9 version to avoid the following error
```
loading model... done
loading wave source... Traceback (most recent call last):
  File "/home/cruisibesares/Downloads/vocal-remover/inference.py", line 172, in <module>
    main()
  File "/home/cruisibesares/Downloads/vocal-remover/inference.py", line 133, in main
    X, sr = librosa.load(
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given
```
Changing the requirements.txt got me working. Cool Project thanks for putting this out there.